import {createRequire} from 'node:module';
import {mkdir,writeFile} from 'node:fs/promises';
import {dirname,join} from 'node:path';
import {fileURLToPath} from 'node:url';
import assert from 'node:assert/strict';
const root=dirname(fileURLToPath(import.meta.url)),project=process.env.APP_ROOT||join(root,'../..');
const {chromium}=createRequire(join(project,'package.json'))('playwright');
const base=process.env.UI_URL||'http://127.0.0.1:4317',output=join(root,'results','journey-'+Date.now());await mkdir(output,{recursive:true});
const browser=await chromium.launch({headless:true}),context=await browser.newContext({viewport:{width:1440,height:1000}}),page=await context.newPage(),steps=[],errors=[];
page.on('pageerror',e=>errors.push(e.message));
async function step(name,fn){await fn();steps.push({name,status:'passed',at:new Date().toISOString()});console.log('PASS '+name);await page.screenshot({path:join(output,steps.length+'-'+name.replace(/\W+/g,'_')+'.png'),fullPage:true});}
const button=name=>page.getByRole('button',{name,exact:true});
const role=async value=>{await page.locator('.demo-strip select').selectOption(value);await page.waitForFunction(v=>document.querySelector('.demo-strip select')?.value===v,value);await page.waitForLoadState('networkidle');};
const goto=async hash=>{await page.goto(base+'/#'+hash,{waitUntil:'domcontentloaded'});await page.locator('#main .loading').waitFor({state:'hidden'});};
try{
 await step('Visible welcome and demo entry',async()=>{await page.goto(base,{waitUntil:'networkidle'});await button('استكشف تجربة علم').click();await button('متابعة بهذا المنظور').waitFor({timeout:15000});await button('متابعة بهذا المنظور').click();await page.locator('.demo-strip').waitFor();});
 await step('Analyst opens real upload flow',async()=>{await role('analyst');await goto('data');await button('رفع قوائم').click();const dialog=page.getByRole('dialog');await dialog.locator('input[type=file]').setInputFiles(join(root,'fixtures/balanced.xlsx'));await dialog.locator('select').selectOption('1');await dialog.locator('input[type=checkbox]').check();await button('بدء الاستيراد').click();await page.getByRole('dialog').waitFor({state:'hidden',timeout:30000});await page.locator('.facts-table tbody tr').first().waitFor();});
 await step('Source inspector and real fact review',async()=>{await page.locator('.source-chip').first().click();await page.getByRole('dialog').waitFor();await page.keyboard.press('Escape');for(let i=0;i<4;i++){await page.getByRole('checkbox',{name:'تحديد الصفحة الحالية',exact:true}).check();await button('تأكيد مراجعة المحدد ومصادره').click();await page.locator('.selection-bar').waitFor({state:'hidden'});if(await button('التالي').isDisabled())break;await button('التالي').click();}const s=await context.request.get(base+'/api/session');const ses=await s.json();const entities=await(await context.request.get(base+'/api/entities')).json();const ds=await(await context.request.get(base+'/api/datasets?entity_id='+entities[0].id)).json();const selected=ds.find(d=>d.document_id);assert.ok(selected.facts.every(f=>f.review_status==='reviewed'),'Visible review left unreviewed facts');assert.equal(ses.user.role,'analyst');});
 await step('Separate CFO approves data in UI',async()=>{await role('cfo');await goto('data');const approveResponse=page.waitForResponse(r=>r.url().includes('/datasets/')&&r.url().endsWith('/approve'));await button('اعتماد البيانات').click();const approved=await approveResponse;assert.equal(approved.status(),200,await approved.text());await page.waitForFunction(()=>[...document.querySelectorAll('button')].some(b=>b.textContent.includes('اعتماد البيانات')&&b.disabled&&b.getAttribute('aria-busy')!=='true'));const analyzeResponse=page.waitForResponse(r=>r.url().includes('/datasets/')&&r.url().endsWith('/analyze'));await button('إعادة التحليل').click();assert.equal((await analyzeResponse).status(),201);await page.waitForLoadState('networkidle');});
 await step('Analyst creates audience-specific report',async()=>{await role('analyst');await goto('reports');await button('إعداد تقرير').click();const dialog=page.getByRole('dialog');const option=dialog.getByRole('button').filter({hasText:'مدير المبيعات'}).first();await option.click();await dialog.getByText('البيانات المجمعة تعطي سياق الشركة فقط.',{exact:false}).waitFor();await button('إنشاء مسودة مخصصة').click();await page.getByRole('dialog').filter({has:page.locator('iframe.report-preview')}).waitFor();const frame=page.frameLocator('iframe.report-preview');await frame.locator('body').waitFor();assert.match(await frame.locator('body').innerText(),/غير متاح من القوائم الإجمالية/);await page.keyboard.press('Escape');});
 await step('Independent CFO approves report and preview renders',async()=>{await role('cfo');await goto('reports');await button('قراءة التقرير').first().click();const response=page.waitForResponse(r=>r.url().includes('/reports/')&&r.url().endsWith('/approve'));await button('اعتماد مستقل').click();const approved=await response;assert.equal(approved.status(),200,await approved.text());await button('اعتماد مستقل').waitFor({state:'hidden'});const text=await page.frameLocator('iframe.report-preview').locator('body').innerText();assert.ok(text.length>1000);assert.match(text,/approved|معتمد/);await page.keyboard.press('Escape');});
 await step('Board reads only approved report',async()=>{await role('board');await goto('reports');await button('قراءة التقرير').first().click();assert.equal(await button('اعتماد مستقل').count(),0);assert.ok((await page.frameLocator('iframe.report-preview').locator('body').innerText()).length>1000);await page.keyboard.press('Escape');await goto('overview');await page.getByRole('heading',{name:'مساحة المجلس',exact:true}).waitFor();assert.equal(await page.locator('.recharts-wrapper').count(),0);assert.equal(await button('رفع قوائم').count(),0);assert.ok(await page.locator('.kpi-card').count()>0);await page.locator('.kpi-card').first().click();assert.equal(await page.getByRole('link',{name:'فتح المستند الأصلي',exact:true}).count(),0);await page.keyboard.press('Escape');});
}catch(e){steps.push({name:'journey failure',status:'failed',error:e.message,url:page.url()});console.error(e);await page.screenshot({path:join(output,'failure.png'),fullPage:true});process.exitCode=1;}finally{await writeFile(join(output,'results.json'),JSON.stringify({base,steps,errors},null,2));console.log(JSON.stringify({output,steps,errors},null,2));await browser.close();}
