import re,unicodedata
def normalize(text):
    text=unicodedata.normalize('NFKC',str(text)).lower().strip()
    text=re.sub(r'[\u064b-\u065f\u0670ـ]','',text).replace('أ','ا').replace('إ','ا').replace('آ','ا').replace('&',' and ')
    return re.sub(r'\s+',' ',re.sub(r'[^\w\s]+',' ',text)).strip()

# Exact normalized aliases: broad fuzzy matching must be reviewed, never guessed.
DEFINITIONS={
'revenue':('الإيرادات','Revenue','revenues|sales|net sales|total revenue|الايرادات|ايرادات'),
'cogs':('تكلفة الإيرادات','Cost of Revenue','cost of revenues|cost of sales|cost of revenue cogs|cogs|تكلفة الايرادات|تكلفة المبيعات'),
'gross_profit':('إجمالي الربح','Gross Profit','مجمل الربح|اجمالي الربح'),
'r_and_d':('البحث والتطوير','Research and development','research development'),
'selling_expenses':('البيع والتسويق','Selling and marketing','selling marketing'),
'ecl_expense':('مصروف خسائر الائتمان','Expected credit losses','expected credit loss|خسائر ائتمانية متوقعة'),
'gna':('مصاريف عمومية وإدارية','General and administrative','general administrative|g a|ga|general and administrative expenses|المصاريف العمومية والادارية'),
'sga':('المصاريف البيعية والإدارية وفق المصدر','SG&A Expenses','SG&A Expenses (incl. R&D and ECL)|sg a expenses incl r d and ecl|sga expenses|sg a|selling general and administrative expenses'),
'depreciation_amortization':('الاستهلاك والإطفاء','Depreciation and amortization','depreciation amortization'),
'impairment':('انخفاض قيمة الأصول','Impairment of non-current assets',''),
'ebit':('الربح التشغيلي','EBIT','ebit operating income|operating profit|operating income|income from operations|الدخل من العمليات التشغيلية'),
'finance_cost':('تكلفة التمويل','Finance costs','finance cost|interest expense finance costs|interest expense|تكاليف التمويل'),
'murabaha_income':('دخل المرابحات','Murabaha deposit income','income from murabaha deposits'),
'nonoperating_income':('إجمالي الدخل غير التشغيلي','Total non-operating income','other income total non operating'),
'ebt':('الربح قبل الزكاة','Profit before zakat','ebt income before zakat|net profit before zakat|income before zakat'),
'zakat':('الزكاة','Zakat','zakat income tax equivalent'),
'net_income':('صافي الربح الموحد','Net Income','net profit|صافي الربح|صافي الدخل'),
'net_income_parent':('ربح مساهمي الأم','Profit attributable to parent','attributable to shareholders of the parent'),
'net_income_nci':('ربح غير المسيطرين','Profit attributable to NCI','attributable to non controlling interests'),
'cash':('النقد وما في حكمه','Cash and cash equivalents','cash cash equivalents|cash equivalents|نقد وما في حكمه'),
'deposits':('ودائع المرابحة','Murabaha deposits','bank deposits|ودائع مرابحة'),
'receivables':('الذمم المدينة وفق المصدر','Accounts receivable','net receivables|accounts receivables|trade receivables|ذمم مدينة|الذمم المدينة'),
'gross_receivables':('إجمالي الذمم قبل المخصص','Gross receivables','gross accounts receivable'),
'ar_allowance':('مخصص الذمم','Receivables allowance','expected credit losses provision|allowance for doubtful accounts'),
'contract_assets':('أصول العقود','Contract assets','contract assets net|موجودات العقود'),
'inventory':('المخزون','Inventory','inventories|مخزون'),
'prepayments':('مقدمات وأصول متداولة أخرى','Prepayments and other current assets','prepayments other current assets|prepaid expenses and other current assets'),
'other_current_assets':('أصول متداولة أخرى','Other Current Assets',''),
'current_assets':('إجمالي الأصول المتداولة','Total Current Assets','current assets|اجمالي الموجودات المتداولة'),
'noncurrent_assets':('إجمالي الأصول غير المتداولة','Total Non-Current Assets',''),
'total_assets':('إجمالي الأصول','Total Assets','اجمالي الموجودات'),
'payables_other':('دائنون ومطلوبات أخرى','Accounts payable and other current liabilities','accounts payable other current liabilities|ذمم دائنة ومطلوبات متداولة اخرى'),
'trade_payables':('ذمم الموردين','Trade payables','accounts payable|supplier payables'),
'borrowing_current':('الاقتراض المتداول','Current borrowings','short term debt|short term debt current portion of lt loan|long term borrowing current|current portion of long term loan'),
'borrowing_noncurrent':('الاقتراض غير المتداول','Non-current borrowings','long term debt|long term borrowing non current|long term borrowings'),
'contract_liabilities':('التزامات العقود','Contract liabilities','مطلوبات العقود'),
'lease_current':('التزام إيجار متداول','Current lease liabilities','lease liabilities current'),
'lease_noncurrent':('التزام إيجار غير متداول','Non-current lease liabilities','lease liabilities non current'),
'current_liabilities':('إجمالي الالتزامات المتداولة','Total Current Liabilities','current liabilities|اجمالي المطلوبات المتداولة'),
'noncurrent_liabilities':('إجمالي الالتزامات غير المتداولة','Total Non-Current Liabilities',''),
'total_liabilities':('إجمالي الالتزامات','Total Liabilities','اجمالي المطلوبات'),
'equity_parent':('ملكية مساهمي الأم','Equity attributable to parent',''),
'equity':('إجمالي حقوق الملكية','Total Equity','equity|shareholders equity|حقوق الملكية'),
'cfo':('التدفق النقدي التشغيلي','Operating cash flow','net cash from operating activities|net cash generated from operating activities|cash flow from operations'),
'cfi':('التدفق الاستثماري','Investing cash flow','net cash from investing activities'),
'cff':('التدفق التمويلي','Financing cash flow','net cash from financing activities'),
'cash_change':('التغير في النقد','Net Change in Cash','net change in cash and cash equivalents'),
'cash_beginning':('نقد أول الفترة','Cash at beginning of year','cash at the beginning of the year'),
'cash_ending':('نقد آخر الفترة','Cash at end of year','cash at the end of the year'),
'cash_fx':('فروق عملة النقد','FX translation differences','net foreign currency exchange'),
'capex':('الإنفاق الرأسمالي النقدي','Capital expenditure','capex|cash capex|cash capital expenditure'),
'credit_sales':('المبيعات الآجلة','Credit sales','net credit sales'),
'purchases':('المشتريات الآجلة','Credit purchases','purchases'),
'eligible_deposits':('ودائع مؤهلة','Eligible deposits',''),
'deposits_eligible':('اعتماد أهلية الودائع','Deposits eligibility approved',''),
'restricted_cash':('نقد مقيد','Restricted cash',''),
'quick_assets':('أصول سريعة معتمدة','Eligible quick assets',''),
'invested_capital':('رأس المال المستثمر','Invested capital',''),
'nopat':('ربح تشغيلي بعد الضريبة معتمد','Approved NOPAT','nopat'),
'organic_revenue_current':('إيراد حالي متماثل','Current like-for-like revenue',''),
'organic_revenue_prior':('إيراد مقارن متماثل','Prior like-for-like revenue',''),
'largest_customer_revenue':('إيراد أكبر عميل','Largest customer revenue',''),
'overdue_receivables':('ذمم تجاوزت الاستحقاق','Past due receivables',''),
'cfads':('نقد متاح لخدمة الدين','Cash available for debt service',''),
'debt_service':('خدمة الدين','Debt service',''),
'covenant_limit':('حد التعهد','Covenant limit',''),
'covenant_actual':('مقياس التعهد','Covenant actual',''),
'customer_revenue':('إيراد العميل','Customer revenue',''),
'customer_service_cost':('تكلفة خدمة العميل','Customer service cost',''),
'forecast_cash':('نقد متوقع معتمد','Approved forecast cash',''),
'action_effect_actual':('أثر إجراء مقاس','Measured action effect',''),
'action_effect_target':('هدف أثر الإجراء','Action effect target',''),
'peer_gross_margin':('وسيط هامش نظراء معتمد','Approved peer gross margin',''),
'peer_count':('عدد النظراء المؤهلين','Eligible peer count',''),
'liquidity_requirements':('متطلبات نقدية موثقة','Documented liquidity requirements',''),
'undrawn_facility':('تسهيل مؤكد غير مسحوب','Confirmed undrawn facility',''),
}
ALIASES={normalize(alias):key for key,(ar,en,aliases) in DEFINITIONS.items() for alias in [key.replace('_',' '),ar,en,*aliases.split('|')] if alias}
def concept(label):return ALIASES.get(normalize(label))
